version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scraping-app
    restart: unless-stopped
    expose:
      - '3045'
    volumes:
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: scraping-nginx
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/www:/var/www
      - ./logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
