version: '3.8'

services:
  scraping-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scraping-app
    restart: unless-stopped
    ports:
      - '3045:3045'
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
